---
title: "Stats 20, S22A -- Homework 3"
author: "Jun Ryu -- 605574052"
date: "`r format(Sys.Date(), '%D')`"
output:
  html_document:
    toc: yes            # creates table of contents
    toc_depth: 4        # toc will include headers <= ####
    toc_float: yes      # toc always on left of page
    code_folding: show  # allows hiding of code
---

## Question 1

### (a)

```{r}

my_min <- function(x, na.rm = FALSE) {
  min = Inf
  if (na.rm) {
    y <- x[!is.na(x)]
    for (i in seq_len(length(y))) {
      if (y[i] < min) {
        min <- y[i]
      }
    }
  } else {
    for (i in seq_len(length(x))) {
      if (x[i] < min | is.na(x[i])) {
        min <- x[i]
      }
    }
  }
 min 
}

```

### (b)

```{r}

my_min(c(4, 1, 0, 2, -3, -5, -4))
my_min(c("bears", "beets", "Battlestar Galactica"))
my_min(7)
my_min(c("Pawnee", "rules", "Eagleton", NA))
my_min(c("Pawnee", "rules", "Eagleton", NA), na.rm = TRUE)
my_min(NA)
my_min(NA, na.rm = TRUE)

```

## Question 2

### (a)

```{r}

fib1 <- 1
fib2 <- 1
full_fib <- c(fib1, fib2)
while (fib1 + fib2 < 500) {
  
  fib2 <- fib1 + fib2
  full_fib <- c(full_fib, fib2)
  fib1 <- fib2 - fib1
}
full_fib

```

### (b)

```{r}


full_fib <- c(1, 1)

while (full_fib[length(full_fib)] + full_fib[length(full_fib)-1] < 500) {
  
  full_fib <- c(full_fib, full_fib[length(full_fib)] + full_fib[length(full_fib) - 1])
}

full_fib

```

### (c)

```{r}
while (full_fib[length(full_fib)] + full_fib[length(full_fib)-1] < 1e9) {
  full_fib <- c(full_fib, full_fib[length(full_fib)] + full_fib[length(full_fib) - 1])
}

length(full_fib)

```
## Question 3

```{r}

my_t <- function(A) {
  A_transpose = matrix(nrow = ncol(A), ncol = nrow(A))
  for (i in 1:nrow(A)){
       for (j in 1:ncol(A)){
             A_transpose[j,i] <- A[i,j]
        }
    }
  A_transpose
}

A = cbind(c(1, 4), c(2, 5), c(3, 6))
my_t(A)
```

## Question 4

### (a)

```{r}

my_cor <- function(x, y, use = "everything") {
  if (use == "everything") {
    r = (sum((x-mean(x))*(y-mean(y))))/(sqrt(sum((x-mean(x))^2))*sqrt(sum((y-mean(y))^2)))
  } else {
    x_new <- x[!(is.na(x) | is.na(y))]
    y_new <- y[!(is.na(x) | is.na(y))]
    r = (sum((x_new-mean(x_new))*(y_new-mean(y_new))))/(sqrt(sum((x_new-mean(x_new))^2))*sqrt(sum((y_new-mean(y_new))^2)))
    
  }
  r
}

```

### (b)

```{r}
linreg <- function(x,y) {
  
  b <- (my_cor(x,y)*sd(y))/sd(x)
  a <- mean(y) - (b*mean(x))
  c(a, b)
  
}
  
```

### (c)

```{r}
x <- c(61,62,63,64,66,68)
y <- c(104,110,125,141,160,170)
linreg(x,y)
```

### (d)

```{r}

linreg_mat <- function(x,y) {
  X <- matrix(nrow = length(x), ncol = 2)
  X[,1] <- 1
  X[,2] <- x
  solve((t(X)%*%X))%*%t(X)%*%y
  
}

```

### (e)

```{r}

linreg_mat(x,y)

```

The result is the same as the values found in part c).


### (f)

The slope in this context represents that per every inch increased in height, you would also expect to gain 10.08824 lbs in weight.


## Question 5

### (a)

```{r}
`%m%` <- function(A, B) {
  if(ncol(A) != nrow(B)) {
    stop("Matrix multiplication cannot be performed")
  }
  C <- matrix(nrow = nrow(A), ncol = ncol(B))
  for (i in 1:nrow(A)) {
    for (j in 1:ncol(B)) {
      C[i,j] <- sum(A[i,]*B[,j])
    
    }
  }
  C
}

```

### (b)

```{r}

X <- matrix(6:1, nrow = 2, byrow = TRUE)
Y <- matrix(1:9, nrow = 3)
X %*% Y
X %m% Y
```


## Question 6

### (a)

```{r}
`%^%` <- function(A, k) {
  B <- diag(3)
  for(i in seq_len(k)) {
    B <- B %m% A
  }
  B
}
```

### (b)
<!-- USE THE CODE CHUNK BELOW -->
```{r Question 6b}

A = cbind(c(0.2,0.6,0.4),c(0.7,0.2,0.1),c(0.1,0.2,0.5))
A %^% 0
A %^% 5
A %^% 50
A %^% 500 
```

## Question 7

```{r}

jerry <- 2:(8 * (5 %% 3)^-2):(7 > 2)
jerry
```

## Question 8

### (a)

```{r}

my_ifelse <- function(test, yes, no) {
  result <- logical(length(test))
  result[which(test)] <- yes[which(test)]
  result[which(!test)] <- no[which(!test)]
  result
}

```


### (b)
```{r}
x <- (1:10) * pi
my_ifelse(x %% 1 >= 0.5, x %/% 1 + 1, x %/% 1)
``` 

### (c)

```{r}
my_abs <- function(x) {
  my_ifelse(x > 0, x, -x)
}

my_sign <- function(x) {
  my_ifelse(x == 0, 0, my_ifelse(x > 0, 1, -1))
  
}

```


## Question 9

### (a)

```{r}

my_row <- function(x) {
  for(i in 1:nrow(x)) {
    for(j in 1:ncol(x)) {
      x[i,j] <- i
    }
  }
 x 
}

```


### (b)

```{r}

my_col <- function(x) {
  for(i in 1:ncol(x)) {
    for(j in 1:nrow(x)) {
      x[j,i] <- i
    }
  }
 x 
}

```


### (c)

```{r}

my_diag <- function(x,nrow = 0,ncol = 0) {
  if(length(x) == 1 & is.null(attributes(x))) {
    sol <- matrix(0, nrow = x, ncol = x)
    for(i in 0:x) {
      sol[i,i] <- 1
    }
  } else if (length(x) > 1 & is.null(attributes(x))) {
    if (missing(nrow) & missing(ncol)) {
      sol <- matrix(0, nrow = length(x), ncol = length(x))
      for(i in 0:length(x)) {
      sol[i,i] <- x[i]
      }
    } else if (!missing(nrow) & !missing(ncol)) {
        sol <- matrix(0, nrow = nrow, ncol = ncol)
        for (i in 0:min(nrow,ncol))
          sol[i,i] <- x[(i+2)%%3+1]
    } else {
        dimension <- max(nrow,ncol)
        sol <- matrix(0, nrow = dimension, ncol = dimension)
        for (i in 0:dimension)
          sol[i,i] <- x[(i+2)%%3+1]
      }
    
  } else {
    nrow <- dim(x)[1]
    ncol <- dim(x)[2]
    sol <- numeric(min(nrow(x),ncol(x)))
    for(i in 0:min(nrow(x),ncol(x))) {
      sol[i] <- x[i,i]
    }
  }
  sol
}

```


## Question 10

### (a)

```{r}

load("dna.Rdata")
locate_motif <- function(strand, motif) {
  index <- numeric(0)
  for(i in 1:(length(strand)-length(motif))) {
    if (all(strand[i:(i+length(motif)-1)] == motif)) {
      index <- c(index,i)
    }
  }
 index 
}

locate_motif(dna1, c("G", "A", "T", "T", "A", "C", "A"))
```

### (b)

```{r}

extract_longest_substring <- function(strand1, strand2) {
  subset <- character(0)
  for(i in 0:length(strand1)) {
      for (j in 0:(length(strand1) - i)) {
        if (all(locate_motif(strand2, strand1[i:i+j]) == numeric(1))) {
          subset <- strand1[i:i+j]
        }
      }
  }
  subset
}

seq1 <- c("A", "C", "A", "G", "T")
seq2 <- c("T", "A", "G", "T", "A")


```


